server:
  host: localhost
  username: username
  password: password
nickname: Bot
botJoinedServerMessage: "Hi %p, i'm here to help you!"
afkMovedMessage: "You were moved because you are muted, if you unmute yourself, you will be moved back"
welcomeUserMessage: "Welcome %p on example.ts"
afkChannel: 0
forbiddenNames:
  forbiddenNames:
    - "Joel"
    - "Jooel"
  forbiddenNamesRegex: "[a-zA-Z1-9|¦ ]*"
  forbiddenNameKickMessage: "You were kicked because your name is not allowed"
mail:
  host: smtp.zoho.eu
  port: 465
  username: user
  password: password
  strategy: SMTP_SSL
  adminMail: test@gmail.com
restHost: example.com